sync:
  fields:
    devices:
      example: "bedroom"
      selector:
        text:
          multiple: true
    allow_downgrade:
      default: false
      selector:
        boolean:
    downloads:
      default: true
      selector:
        boolean:
install:
  fields:
    packages:
      required: true
      example: "org.xbmc.kodi"
      selector:
        text:
          multiple: true
    devices:
      example: "bedroom"
      selector:
        text:
          multiple: true
